### ISSUE TITLE
Update terraform code to get ssh key for nodes 

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/terraform-google-gke#10]
Hello team,

Please udpate terraform module to provide ssh key as terraform ouput. We will use that terraform output on cluster infra to ssh into one of the nodes. Please make sure it's documented for other users of our terraform module

Thank you

**Comment by Ahmeddevops-Github** [comment]
When trying to clone the "terraform-google-gke". I received an permission/access denied.

**Comment by fuchicorp-manage** [comment]
You should have all access. It should be from your end!! Please make sure you upload your public key to your profile

Reference to this documentation 
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by turanmehmet** [comment]
Hi Farkhod, how do we test the changes? Should we work on our cluster?

**Comment by ksalrin** [comment]
- Add the ssh-key to the node config
- Output the node ips

**Comment by turanmehmet** [comment]
Farkhod suggested me to find a way to output node instances using `gcloud compute instances list` command and filter them. I couldn't put in terraform code

**Comment by fsadykov** [comment]
Please see the option from stacjoverflow
https://stackoverflow.com/questions/38645002/how-to-add-an-ssh-key-to-an-gcp-instance-using-terraform

You will need to add metadata to cluster with ssh-keys
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#metadata

**Comment by turanmehmet** [comment]
I still couldn't connect to my nodes for some reason
![image](https://user-images.githubusercontent.com/18574618/125879764-67c61ef0-507f-4a95-909d-36862c953b29.png)

**Comment by turanmehmet** [comment]
I added the following 
```
      metadata = {
        ssh-keys = "${var.gce_ssh_user}:${file(var.gce_ssh_pub_key_file)}"
      }
```
Check the nodes to see if terraform created the metadata

![image](https://user-images.githubusercontent.com/18574618/125939153-af362e80-26e8-4b1a-9924-d41ddbfa9e72.png)

But still couldn't connect to nodes

**Comment by turanmehmet** [comment]
Wiki page
https://github.com/fuchicorp/terraform-google-gke/wiki/Update-terraform-code-to-get-ssh-key-for-nodes
