### ISSUE TITLE
Add line to disable Automatic Upgrades

### ISSUE THREAD

**Issue by ksalrin** [fuchicorp/terraform-google-gke#6]
Hello Team!

We have recently ran into a problem with our nodes automatically upgrading from v1.16 to v1.17 without our knowledge.  Please add a line to the module to ensure that we are using the version we are specifying only (v1.16) and disable any automation updates. 

Thank you!
Kelly Salrin

**Comment by slimflex2** [comment]
wiki: https://github.com/fuchicorp/terraform-google-gke
